# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0

linters-settings:
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 4
  lll:
    line-length: 140
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    # - dupl
    # - errcheck
    # - exhaustive
    # - exportloopref
    # - funlen
    # - gci
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    - goconst
    # - gocritic
    # - gocyclo
    # - godox
    - gofmt
    # - gofumpt
    - goheader
    # - goimports
    # - gomnd
    # - gomodguard
    # - goprintffuncname
    # - gosec
    # - gosimple
    # - govet
    # - ineffassign
    # - lll
    - misspell
    # - nakedret
    # - nestif
    # - nlreturn
    # - noctx
    - nolintlint
    - prealloc
    # - revive
    # - rowserrcheck
    # - sqlclosecheck
    # - staticcheck
    # - structcheck
    # - stylecheck
    # - typecheck
    # - unconvert
    # - unparam
    - unused
    - varcheck
    # - whitespace
    # - wsl

run:
  concurrency: 4
  timeout: 5m