# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0

version: 2
project_name: gnmic
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/openconfig/gnmic/pkg/version.Version={{.Version}} -X github.com/openconfig/gnmic/pkg/version.Commit={{.ShortCommit}} -X github.com/openconfig/gnmic/pkg/version.Date={{.Date}} -X github.com/openconfig/gnmic/pkg/version.GitURL={{.GitURL}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
dockers_v2:
  - id: gnmic
    ids:
      - gnmic
    dockerfile: goreleaser-alpine.dockerfile
    images:
      - ghcr.io/openconfig/gnmic
    tags:
      - '{{ replace .Version "v" "" }}'
      - "{{ if not .IsSnapshot }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: false
    build_args:
      ALPINE_VERSION: "{{ .Env.ALPINE_VERSION }}"
    flags:
      - "--provenance=false"
  - id: gnmic-scratch
    ids:
      - gnmic
    dockerfile: goreleaser-scratch.dockerfile
    images:
      - ghcr.io/openconfig/gnmic
    tags:
      - '{{ replace .Version "v" "" }}-scratch'
      - "{{ if not .IsSnapshot }}latest-scratch{{ end }}"
    platforms:
      - linux/amd64
    sbom: false
    flags:
      - "--provenance=false"
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armv7
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}"
changelog:
  use: github-native

nfpms:
  - id: gnmic
    file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armv7
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    vendor: gnmic
    homepage: https://gnmic.openconfig.net
    maintainer: Karim Radhouani <medkarimrdi@gmail.com>, Roman Dodin <dodin.roman@gmail.com>
    description: gNMI CLI client and collector
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
