# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0

project_name: gnmic
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/openconfig/gnmic/pkg/app.version={{.Version}} -X github.com/openconfig/gnmic/pkg/app.commit={{.ShortCommit}} -X github.com/openconfig/gnmic/pkg/app.date={{.Date}} -X github.com/openconfig/gnmic/pkg/app.gitURL={{.GitURL}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - gnmic
    image_templates:
      - &amd64_latest_image "ghcr.io/openconfig/gnmic:latest-amd64"
      - &amd64_versioned_image 'ghcr.io/openconfig/gnmic:{{ replace .Version "v" ""}}-amd64'
    dockerfile: goreleaser-alpine.dockerfile
    skip_push: false
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  - goos: linux
    goarch: arm64
    ids:
      - gnmic
    image_templates:
      - &arm64_latest_image "ghcr.io/openconfig/gnmic:latest-arm64"
      - &arm64_versioned_image 'ghcr.io/openconfig/gnmic:{{ replace .Version "v" ""}}-arm64'
    dockerfile: goreleaser-alpine.dockerfile
    skip_push: false
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
  - goos: linux
    goarch: amd64
    ids:
      - gnmic
    image_templates:
      - "ghcr.io/openconfig/gnmic:latest-scratch"
      - 'ghcr.io/openconfig/gnmic:{{ replace .Version "v" ""}}-scratch'
    dockerfile: goreleaser-scratch.dockerfile
    skip_push: false
docker_manifests:
  - name_template: 'ghcr.io/openconfig/gnmic:{{ replace .Version "v" "" }}'
    image_templates:
      - *amd64_versioned_image
      - *arm64_versioned_image
  - name_template: "{{- if not .IsSnapshot}}ghcr.io/openconfig/gnmic:latest{{- end}}"
    image_templates:
      - *amd64_latest_image
      - *arm64_latest_image
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armv7
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: gnmic
    file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armv7
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    vendor: gnmic
    homepage: https://gnmic.openconfig.net
    maintainer: Karim Radhouani <medkarimrdi@gmail.com>, Roman Dodin <dodin.roman@gmail.com>
    description: gNMI CLI client and collector
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
