# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0

username: admin
password: NokiaSrl1!
insecure: true
encoding: json_ietf
log: true

targets:
  # Add targets configuration here
  # e.g:
  # 192.168.1.131:57400:
  #   username: gnmic
  #   password: secret_password


subscriptions:
  # Add subscriptions configuration here
  # e.g:
  # sub1:
  #   paths:
  #     - /interface/statistics
  #   stream-mode: sample
  #   sample-interval: 1s

outputs:
  prom-output:
    type: prometheus
    listen: "gnmic1:9804"
    service-registration:
      address: consul-agent:8500
